### ISSUE TITLE
ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s) , but the saved weights have 1 element(s).

### ISSUE THREAD

**Issue by uysalmustafa** [xuannianz/EfficientDet#152]
Hi,
I've been trying to train dataset using 
`python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 4 --steps 100 coco C:/Users/mustafa/Downloads/deneme.v1-1.coco/datasets/coco`

And I've seen this error. 

> Traceback (most recent call last):
>   File "train.py", line 381, in <module>
>     main()
>   File "train.py", line 333, in main
>     model.load_weights(args.snapshot, by_name=True)
>   File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> ine\training.py", line 271, in load_weights
>     return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
>   File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> ine\network.py", line 1276, in load_weights
>     f, self.layers, skip_mismatch=skip_mismatch)
>   File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\sav
> ing\hdf5_format.py", line 769, in load_weights_from_hdf5_group_by_name
>     str(len(weight_values)) + ' element(s).')
> ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s)
> , but the saved weights have 1 element(s).
> 

I've tried to set
weighted_bifpn = False
and
os.environ['CUDA_VISIBLE_DEVICES'] = ''
but they didn't work. 
My GPU doesn't support CUDA.

Edit: I've fixed it. But I've tried this on Colab

`!python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --weighted-bifpn --random-transform --compute-val-loss --freeze-bn --batch-size 4 --steps 100 coco datasets/coco`

**Comment by majnas** [comment]
this is my problem also
ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s), but the saved weights have 1 element(s).

**Comment by majnas** [comment]
> Hi,
> I've been trying to train dataset using
> `python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 4 --steps 100 coco C:/Users/mustafa/Downloads/deneme.v1-1.coco/datasets/coco`
> 
> And I've seen this error.
> 
> > Traceback (most recent call last):
> > File "train.py", line 381, in 
> > main()
> > File "train.py", line 333, in main
> > model.load_weights(args.snapshot, by_name=True)
> > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> > ine\training.py", line 271, in load_weights
> > return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
> > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> > ine\network.py", line 1276, in load_weights
> > f, self.layers, skip_mismatch=skip_mismatch)
> > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\sav
> > ing\hdf5_format.py", line 769, in load_weights_from_hdf5_group_by_name
> > str(len(weight_values)) + ' element(s).')
> > ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s)
> > , but the saved weights have 1 element(s).
> 
> I've tried to set
> weighted_bifpn = False
> and
> os.environ['CUDA_VISIBLE_DEVICES'] = ''
> but they didn't work.
> My GPU doesn't support CUDA.

did u solve your problem?

**Comment by uysalmustafa** [comment]
> > Hi,
> > I've been trying to train dataset using
> > `python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 4 --steps 100 coco C:/Users/mustafa/Downloads/deneme.v1-1.coco/datasets/coco`
> > And I've seen this error.
> > > Traceback (most recent call last):
> > > File "train.py", line 381, in
> > > main()
> > > File "train.py", line 333, in main
> > > model.load_weights(args.snapshot, by_name=True)
> > > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> > > ine\training.py", line 271, in load_weights
> > > return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
> > > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> > > ine\network.py", line 1276, in load_weights
> > > f, self.layers, skip_mismatch=skip_mismatch)
> > > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\sav
> > > ing\hdf5_format.py", line 769, in load_weights_from_hdf5_group_by_name
> > > str(len(weight_values)) + ' element(s).')
> > > ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s)
> > > , but the saved weights have 1 element(s).
> > 
> > 
> > I've tried to set
> > weighted_bifpn = False
> > and
> > os.environ['CUDA_VISIBLE_DEVICES'] = ''
> > but they didn't work.
> > My GPU doesn't support CUDA.
> 
> did u solve your problem?

I've fixed it on Colab. But I hope it will work on your computer, as well. I've edited post.

**Comment by majnas** [comment]
> > > Hi,
> > > I've been trying to train dataset using
> > > `python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 4 --steps 100 coco C:/Users/mustafa/Downloads/deneme.v1-1.coco/datasets/coco`
> > > And I've seen this error.
> > > > Traceback (most recent call last):
> > > > File "train.py", line 381, in
> > > > main()
> > > > File "train.py", line 333, in main
> > > > model.load_weights(args.snapshot, by_name=True)
> > > > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> > > > ine\training.py", line 271, in load_weights
> > > > return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
> > > > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\eng
> > > > ine\network.py", line 1276, in load_weights
> > > > f, self.layers, skip_mismatch=skip_mismatch)
> > > > File "C:\Users\mustafa\anaconda3\lib\site-packages\tensorflow\python\keras\sav
> > > > ing\hdf5_format.py", line 769, in load_weights_from_hdf5_group_by_name
> > > > str(len(weight_values)) + ' element(s).')
> > > > ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s)
> > > > , but the saved weights have 1 element(s).
> > > 
> > > 
> > > I've tried to set
> > > weighted_bifpn = False
> > > and
> > > os.environ['CUDA_VISIBLE_DEVICES'] = ''
> > > but they didn't work.
> > > My GPU doesn't support CUDA.
> > 
> > 
> > did u solve your problem?
> 
> I've fixed it on Colab. But I hope it will work on your computer, as well. I've edited post.

Didn't solve my problem.
when i use imagenet snapshot it works. but don't work with efficientdet-d0.h5

**Comment by eypros** [comment]
The issue here is that probably you are using weights from a model which contains the weighted biFPN while you use a model which does not use weighted version. Check this out.

**Comment by ankitchandracs** [comment]
i am facing this issue when i am trying to load the model. can anyone suggest solution?
